Add libssl3 to docker image so mender-sign works
mendersoftware/mender-ci-workflows pull request #30
Opened 2024-05-07 19:37 UTC by chriswiggins

Mender-sign doesn't work in the latest master because libssl3 is missing.

This adds it to the docker image

2024-05-08 06:47 UTC, lluiscampos requested changes
Thank you @chriswiggins for your addition. It looks good to me!

Our commit linting is a bit picky, CI is failing because you don't have a "Ticket" tag. Please add `Ticket: None` to your commit and we'll be good to go

2024-05-29 20:44 UTC, chazh commented
Hello, is there any chance that this can be completed? I am also running into the same problem.

2024-05-29 21:21 UTC, chriswiggins commented
Sorry I've updated this now. Please let me know if all ok

2024-05-30 06:45 UTC, lluiscampos approved these changes
> Sorry I've updated this now. Please let me know if all ok

Thank you!

After you complied with our license by signing the commit, I took the liberty of amending your commit (re-ordering the tags and modifying your signed-off e-mail to match the author one) and pushed to your fork.

CI is happy now.

Thanks @chriswiggins for your contribution!

2024-05-30 06:47 UTC, merged